### ISSUE TITLE
Problem with docxsphinx

### ISSUE THREAD

**Issue by aurel-l** [lbologna/hbp-sp6-guidebook#51]
I had a small issue generating the HTML from an unmodified clone of the repo.

I solved it by commenting out `'docxsphinx'` from `/source/conf.py`.

Depending on what is wanted it would be good to either specify in the readme that docxsphinx need to be installed previously (from [here](https://github.com/mherkazandjian/docxsphinx)) I guess). Or just to drop that dependency.

**Comment by lbologna** [comment]
Hello,

The package is only needed if one wants to generate a .doc file from the .rst
I will drop the dependency and put a comment in the readme.

Thank you

**Comment by lbologna** [comment]
Extension commented out in the conf.py file and README file updated.
Closing issue.
