### ISSUE TITLE
Images missing in Configure and run a rat hippocampus CA1 region using preconfigured HBP model and data

### ISSUE THREAD

**Issue by lbologna** [lbologna/hbp-sp6-guidebook#59]
Hello,

@antonelepfl I pulled the code after accepting the pull request but it seems two images are missing:
online_usecases/brain_area_circuit_in_silico_experiments/hippocampus/configure_run_brainregion_preconf_model_data/images/view_simulation_top.png
and
online_usecases/brain_area_circuit_in_silico_experiments/hippocampus/configure_run_brainregion_preconf_model_data/images/view_simulation_middle.png

Could you please have a look?

Thank you

**Comment by antonelepfl** [comment]
Indeed I removed some images. Here you have the new PR https://github.com/lbologna/hbp-sp6-guidebook/pull/60
Are you able to test it locally first? When I build it I don't see any error.

**Comment by lbologna** [comment]
Yes I built it locally and I got the errors about the images, but now I don't get any error/warning anymore.
I pushed the html to the gh-pages/deployment branch:
https://lbologna.github.io/hbp-sp6-guidebook/

**Comment by lbologna** [comment]
Solved. Closing the issue.
